// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikvjnrtwfvudqsulwfpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrdmpucnR3ZnZ1ZHFzdWx3ZnBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MDk1NzksImV4cCI6MjA2NTE4NTU3OX0.VEm9rih9ITdkt9pBrWChDzwmpljmSjlQFMPeuAOK0vI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);